import numpy as np

legolas_namelist_items = {
    "gridlist": [
        ("geometry", str),
        ("x_start", (int, np.integer, float)),
        ("x_end", (int, np.integer, float)),
        ("gridpoints", (int, np.integer)),
        ("force_r0", bool),
        ("coaxial", bool),
        ("symmetric_grid", bool),
    ],
    "equilibriumlist": [
        ("equilibrium_type", str),
        ("boundary_type", str),
        ("use_defaults", bool),
    ],
    "savelist": [
        ("write_matrices", bool),
        ("write_eigenvectors", bool),
        ("write_residuals", bool),
        ("write_background", bool),
        ("write_eigenfunctions", bool),
        ("write_derived_eigenfunctions", bool),
        ("show_results", bool),
        ("basename_datfile", str),
        ("output_folder", str),
        ("logging_level", (int, np.integer)),
        ("write_eigenfunction_subset", bool),
        ("eigenfunction_subset_center", complex),
        ("eigenfunction_subset_radius", (int, np.integer, float)),
        ("write_iv_snapshots", bool),
    ],
    "physicslist": [
        ("physics_type", str),
        ("mhd_gamma", float),
        ("incompressible", bool),
        ("dropoff_edge_dist", (int, np.integer, float)),
        ("dropoff_width", (int, np.integer, float)),
        ("flow", bool),
        ("radiative_cooling", bool),
        ("heating", bool),
        ("force_thermal_balance", bool),
        ("ncool", (int, np.integer)),
        ("cooling_curve", str),
        ("external_gravity", bool),
        ("parallel_conduction", bool),
        ("perpendicular_conduction", bool),
        ("fixed_tc_para_value", (int, np.integer, float)),
        ("fixed_tc_perp_value", (int, np.integer, float)),
        ("resistivity", bool),
        ("fixed_resistivity_value", (int, np.integer, float)),
        ("use_eta_dropoff", bool),
        ("viscosity", bool),
        ("viscosity_value", (int, np.integer, float)),
        ("viscous_heating", bool),
        ("hall_mhd", bool),
        ("hall_dropoff", bool),
        ("elec_inertia", bool),
        ("inertia_dropoff", bool),
        ("electron_fraction", (int, np.integer, float)),
        ("basis_functions", list),
    ],
    "unitslist": [
        ("unit_numberdensity", (int, np.integer, float)),
        ("unit_density", (int, np.integer, float)),
        ("unit_temperature", (int, np.integer, float)),
        ("unit_magneticfield", (int, np.integer, float)),
        ("unit_length", (int, np.integer, float)),
        ("mean_molecular_weight", (int, np.integer, float)),
    ],
    "solvelist": [
        ("solver", str),
        ("arpack_mode", str),
        ("number_of_eigenvalues", (int, np.integer)),
        ("which_eigenvalues", str),
        ("maxiter", (int, np.integer)),
        ("sigma", (int, np.integer, float, complex)),
        ("ncv", (int, np.integer)),
        ("tolerance", (int, np.integer, float)),
    ],
    "ivplist": [
        ("enabled", bool),
        ("alpha", (int, np.integer, float)),
        ("t_end", (int, np.integer, float)),
        ("n_steps", (int, np.integer)),
        ("n_snapshots", (int, np.integer)),
        ("snapshot_stride", (int, np.integer)),
    ],
}

amrvac_namelist_items = {
    "filelist": [
        ("base_filename", str),
        ("restart_from_file", str),
        ("typefilelog", str),
        ("snapshotnext", (int, np.integer)),
        ("slicenext", (int, np.integer)),
        ("firstprocess", bool),
        ("reset_grid", bool),
        ("convert", bool),
        ("convert_type", str),
        ("slice_type", str),
        ("collapse_type", str),
        ("autoconvert", bool),
        ("sliceascii", bool),
        ("saveprim", bool),
        ("nwauxio", (int, np.integer)),
        ("w_convert_factor", (list, np.ndarray)),
        ("time_convert_factor", (int, np.integer, float)),
        ("length_convert_factor", (int, np.integer, float)),
        ("level_io", (int, np.integer)),
        ("level_io_min", (int, np.integer)),
        ("level_io_max", (int, np.integer)),
        ("nocartesian", bool),
        ("w_write", list),
        ("writelevel", list),
        ("writespshift", list),
    ],
    "savelist": [
        ("ditsave_log", (int, np.integer)),
        ("dtsave_dat", (int, np.integer, float)),
    ],
    "stoplist": [
        ("it_max", (int, np.integer)),
        ("time_max", (int, np.integer, float)),
        ("wall_time_max", (int, np.integer, float)),
        ("dtmin", (int, np.integer, float)),
        ("it_init", (int, np.integer)),
        ("time_init", (int, np.integer, float)),
        ("reset_time", bool),
        ("reset_it", bool),
        ("final_dt_reduction", bool),
    ],
    "methodlist": [
        ("time_stepper", str),
        ("time_integrator", str),
        ("flux_scheme", list),
        ("limiter", list),
        ("gradient_limiter", str),
        ("loglimit", list),
        ("flatsh", bool),
        ("flatcd", bool),
        ("mcbeta", (int, np.integer, float)),
        ("typeentropy", str),
        ("entropycoef", (list, np.ndarray)),
        ("typetvd", str),
        ("typeaverage", str),
        ("typeboundspeed", str),
        ("tvdlfeps", (int, np.integer, float)),
        ("flathllc", bool),
        ("nxdiffusehllc", (int, np.integer)),
        ("source_split_usr", bool),
        ("typesourcesplit", str),
        ("dimsplit", bool),
        ("typedimsplit", str),
        ("small_density", (int, np.integer, float)),
        ("small_pressure", (int, np.integer, float)),
        ("small_temperature", (int, np.integer, float)),
        ("small_values_method", str),
        ("small_values_daverage", (int, np.integer)),
        ("check_small_values", bool),
        ("fix_small_values", bool),
        ("trace_small_values", bool),
        ("small_values_fix_iw", list),
        ("typegrad", str),
        ("typediv", str),
        ("typecurl", str),
    ],
    "boundlist": [
        ("nghostcells", (int, np.integer)),
        ("typeboundary_min1", list),
        ("typeboundary_max1", list),
        ("typeboundary_min2", list),
        ("typeboundary_max2", list),
        ("typeboundary_min3", list),
        ("typeboundary_max3", list),
        ("internalboundary", bool),
        ("ghost_copy", bool),
    ],
    "meshlist": [
        ("refine_max_level", (int, np.integer)),
        ("domain_nx1", (int, np.integer)),
        ("domain_nx2", (int, np.integer)),
        ("domain_nx3", (int, np.integer)),
        ("block_nx1", (int, np.integer)),
        ("block_nx2", (int, np.integer)),
        ("block_nx3", (int, np.integer)),
        ("xprobmin1", (int, np.integer, float)),
        ("xprobmax1", (int, np.integer, float)),
        ("xprobmin2", (int, np.integer, float)),
        ("xprobmax2", (int, np.integer, float)),
        ("xprobmin3", (int, np.integer, float)),
        ("xprobmax3", (int, np.integer, float)),
        ("refine_criterion", (int, np.integer)),
        ("nbufferx1", (int, np.integer)),
        ("nbufferx2", (int, np.integer)),
        ("nbufferx3", (int, np.integer)),
        ("max_blocks", (int, np.integer)),
        ("amr_wavefilter", (list, np.ndarray)),
        ("refine_threshold", (list, np.ndarray)),
        ("derefine_ratio", (list, np.ndarray)),
        ("w_refine_weight", (list, np.ndarray)),
        ("logflag", list),
        ("iprob", (int, np.integer)),
        ("prolongprimitive", bool),
        ("coarsenprimitive", bool),
        ("tfixgrid", (int, np.integer, float)),
        ("itfixgrid", (int, np.integer)),
        ("ditregrid", (int, np.integer)),
        ("stretch_dim", list),
        ("stretch_uncentered", bool),
        ("qstretch_baselevel", (int, np.integer, float)),
        ("nstretchedblocks_baselevel", (int, np.integer)),
    ],
    "paramlist": [
        ("dtpar", (int, np.integer, float)),
        ("courantpar", (int, np.integer, float)),
        ("typecourant", str),
        ("dtdiffpar", (int, np.integer, float)),
        ("slowsteps", (int, np.integer)),
    ],
    "hd_list": [
        ("hd_energy", str),
        ("hd_n_tracer", (int, np.integer)),
        ("hd_gamma", (int, np.integer, float)),
        ("hd_adiab", (int, np.integer, float)),
        ("hd_dust", bool),
        ("hd_thermal_conduction", bool),
        ("hd_radiative_cooling", bool),
        ("hd_gravity", bool),
        ("hd_viscosity", bool),
        ("hd_particles", bool),
        ("He_abundance", (int, np.integer, float)),
        ("SI_unit", bool),
    ],
    "mhd_list": [
        ("mhd_energy", bool),
        ("mhd_n_tracer", (int, np.integer)),
        ("mhd_gamma", (int, np.integer, float)),
        ("mhd_adiab", (int, np.integer, float)),
        ("mhd_eta", (int, np.integer, float)),
        ("mhd_eta_hyper", (int, np.integer, float)),
        ("mhd_etah", (int, np.integer, float)),
        ("mhd_glm_alpha", (int, np.integer, float)),
        ("mhd_glm_extended", bool),
        ("mhd_magnetofriction", bool),
        ("mhd_thermal_conduction", bool),
        ("mhd_radiative_cooling", bool),
        ("mhd_Hall", bool),
        ("mhd_gravity", bool),
        ("mhd_viscosity", bool),
        ("mhd_particles", bool),
        ("mhd_4th_order", bool),
        ("mhd_internal_e", bool),
        ("mhd_hydrodynamic_e", bool),
        ("mhd_semirelativistic", bool),
        ("mhd_boris_simplification", bool),
        ("mhd_reduced_c", (int, np.integer, float)),
        ("mhd_trac", bool),
        ("mhd_trac_type", (int, np.integer)),
        ("mhd_trac_mask", (int, np.integer, float)),
        ("mhd_trac_finegrid", (int, np.integer)),
        ("typedivbfix", str),
        ("type_ct", str),
        ("source_split_divb", bool),
        ("boundary_divbfix", list),
        ("divbdiff", (int, np.integer, float)),
        ("typedivbdiff", str),
        ("clean_initial_divb", bool),
        ("divbwave", bool),
        ("B0field", bool),
        ("B0field_forcefree", bool),
        ("Bdip", (int, np.integer, float)),
        ("Bquad", (int, np.integer, float)),
        ("Boct", (int, np.integer, float)),
        ("Busr", (int, np.integer, float)),
        ("He_abundance", (int, np.integer, float)),
        ("SI_unit", bool),
        ("has_equi_rho_and_p", bool),
        ("mhd_equi_thermal", bool),
        ("mhd_dump_full_vars", bool),
    ],
    "rc_list": [
        ("coolcurve", str),
        ("ncool", (int, np.integer)),
        ("tlow", (int, np.integer, float)),
        ("Tfix", bool),
        ("rc_split", bool),
        ("rad_cut", bool),
        ("rad_cut_hgt", (int, np.integer, float)),
        ("rad_cut_dey", (int, np.integer, float)),
    ],
    "tc_list": [
        ("tc_perpendicular", bool),
        ("tc_saturate", bool),
        ("tc_slope_limiter", str),
        ("tc_k_para", (int, np.integer, float)),
        ("tc_k_perp", (int, np.integer, float)),
    ],
    "vc_list": [
        ("vc_mu", (int, np.integer, float)),
        ("vc_4th_order", bool),
        ("vc_split", bool),
        ("viscInDiv", bool),
    ],
    "grav_list": [
        ("grav_split", bool),
    ],
}

legolas_to_amrvac_translation = {
    "geometries": {"Cartesian": "Cartesian", "cylindrical": "polar"},
}