namelist_items = {
    "gridlist": [
        ("geometry", str),
        ("x_start", (int, float)),
        ("x_end", (int, float)),
        ("gridpoints", int),
        ("mesh_accumulation", bool),
        ("ev_1", (int, float)),
        ("ev_2", (int, float)),
        ("sigma_1", (int, float)),
        ("sigma_2", (int, float)),
        ("force_r0", bool),
    ],
    "equilibriumlist": [
        ("equilibrium_type", str),
        ("boundary_type", str),
        ("use_defaults", bool),
        ("remove_spurious_eigenvalues", bool),
        ("nb_spurious_eigenvalues", int),
    ],
    "savelist": [
        ("write_matrices", bool),
        ("write_eigenfunctions", bool),
        ("show_results", bool),
        ("basename_datfile", str),
        ("basename_logfile", str),
        ("output_folder", str),
        ("logging_level", int),
    ],
    "physicslist": [
        ("mhd_gamma", float),
        ("flow", bool),
        ("radiative_cooling", bool),
        ("ncool", int),
        ("cooling_curve", str),
        ("external_gravity", bool),
        ("thermal_conduction", bool),
        ("use_fixed_tc_para", bool),
        ("fixed_tc_para_value", (int, float)),
        ("use_fixed_tc_perp", bool),
        ("fixed_tc_perp_value", (int, float)),
        ("resistivity", bool),
        ("use_fixed_resistivity", bool),
        ("fixed_eta_value", (int, float)),
        ("use_eta_dropoff", bool),
        ("dropoff_edge_dist", (int, float)),
        ("dropoff_width", (int, float)),
    ],
    "unitslist": [
        ("cgs_units", bool),
        ("unit_density", (int, float)),
        ("unit_temperature", (int, float)),
        ("unit_magneticfield", (int, float)),
        ("unit_length", (int, float)),
    ],
    "solvelist": [
        ("solver", str),
        ("arpack_mode", str),
        ("number_of_eigenvalues", int),
        ("which_eigenvalues", str),
        ("maxiter", int),
        ("sigma", (int, float, complex)),
    ],
}
