message(STATUS "Finding LAPACK")

IF($ENV{LAPACK_LIBRARIES})
    message(STATUS "LAPACK found: $ENV{LAPACK_LIBRARIES}")
    set(LAPACK_FOUND TRUE)
    set(LAPACK_LIBRARIES $ENV{LAPACK_LIBRARIES})
    return()
ENDIF()

find_package(LAPACK REQUIRED)
if (${LAPACK_FOUND})
    message(STATUS "Found LAPACK: ${LAPACK_LIBRARIES}")
else()
    message(STATUS "Try setting $LAPACK_LIBRARIES")
endif()